package com.cardinalhealth.orderexpress.utils.analytics

import com.cardinalhealth.orderexpress.core.common.COMMA_SEPARATOR
import com.cardinalhealth.orderexpress.core.common.EMPTY_STRING
import com.cardinalhealth.orderexpress.core.common.THREE
import com.cardinalhealth.orderexpress.core.common.ZERO

/**
 * This class helps you to map store fronts based on programming code and member group list
 */
class StorefrontUtils {
    private val CIM_PROGRAMMING_CODE = "80"
    private val ASSIST_PROGRAMMING_CODE = "79"
    private val PR_PROGRAMMING_CODE = "66"

    private val CIM_STORE_FRONT = "CIM"
    private val PR_STORE_FRONT = "PR"
    private val ASSIST_STORE_FRONT = "Assist"

    private val RETAIL_INDEPENDENT_USER_GROUP = "RI"
    private val SPD_USER_GROUP = "SPD"
    private val SS_SPD_USER_GROUP = "SS_SPD"
    private val ACUTE_CARE_USER_GROUP = "AC"
    private val RETAIL_ADMIN_USER_GROUP = "WEB_ORDERING_ADMIN"
    private val ASSIST_ADMIN_USER_GROUP = "WEB_ORDERING_AA"


    private val ROLE_ADMIN_RI_CAPS =
        "G-EXT-RWO-RETAIL_INDEPENDENT_ORDERING__PORTAL__ROLE__ADMIN__"
    private val ROLE_ADMIN_RI_SMALL =
        "g-ext-rwo-retail_independent_ordering__portal__role__admin__"
    private val ROLE_BUYER_RI_CAPS =
        "G-EXT-RWO-RETAIL_INDEPENDENT_ORDERING__PORTAL__ROLE__BUYER__"
    private val ROLE_BUYER_RI_SMALL =
        "g-ext-rwo-retail_independent_ordering__portal__role__buyer__"
    private val ROLE_READONLY_RI_CAPS =
        "G-EXT-RWO-RETAIL_INDEPENDENT_ORDERING__PORTAL__ROLE__READONLY__"
    private val ROLE_READONLY_RI_SMALL =
        "g-ext-rwo-retail_independent_ordering__portal__role__readonly__"
    private val ROLE_ADMIN_RI_NEW_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__RETAIL_INDEPENDENT__RETAIL_INDEPENDENT_ORDERING__ADMIN"
    private val ROLE_BUYER_RI_NEW_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__RETAIL_INDEPENDENT__RETAIL_INDEPENDENT_ORDERING__BUYER"
    private val ROLE_NON_ORDERING_RI_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__RETAIL_INDEPENDENT__RETAIL_INDEPENDENT_ORDERING__NON_ORDERING"

    private val ROLE_ADMIN_SPD_CAPS =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ORDERING__ADMIN"
    private val ROLE_ADMIN_SPD_SMALL =
        "g-ext-ga-specialty_pharmaceutical_serv__specialty_pharmaceutical_services__specialty_pharmaceutical_services_ordering__admin"
    private val ROLE_BUYER_SPD_CAPS =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ORDERING__BUYER"
    private val ROLE_BUYER_SPD_SMALL =
        "g-ext-ga-specialty_pharmaceutical_serv__specialty_pharmaceutical_services__specialty_pharmaceutical_services_ordering__buyer"
    private val ROLE_READONLY_SPD_CAPS =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ORDERING__READ_ONLY"
    private val ROLE_READONLY_SPD_SMALL =
        "g-ext-ga-specialty_pharmaceutical_serv__specialty_pharmaceutical_services__specialty_pharmaceutical_services_ordering__read_only"

    private val ROLE_ASR_SPD_CAPS =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ORDERING__ASR"
    private val ROLE_ASR_SPD_SMALL =
        "g-ext-ga-specialty_pharmaceutical_serv__specialty_pharmaceutical_services__specialty_pharmaceutical_services_ordering__asr"
    private val RETAIL_ADMIN_UNIQUE_NAME_SUFFIX = ".ADMIN"
    private val ROLE_READONLY_ADMIN =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__READONLY"
    private val ROLE_READONLY_ADMIN_OLD =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION_READONLY_"
    private val ROLE_ADMINROLE_ADMIN =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__ADMIN"
    private val ROLE_ADMINROLE_OE_RUN_ADMIN =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__OE_RUN_ADMIN"
    private val ROLE_ADMIN_READONLY_ROLE =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__READ_ONLY"
    private val ROLE_ADMIN_PO_EXPORT =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__PO_EXPORT"
    private val ROLE_ADMIN_ORG_MDM_USER =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__MDM_ORG_ADMIN"
    private val ROLE_ADMIN_ORG_TIER_REBATE_USER =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__TIERED_REBATE"

    private val ROLE_ASR_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__ASR"
    private val ROLE_ADMIN_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__ADMIN"
    private val ROLE_BUYER_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__BUYER"
    private val ROLE_READONLY_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__READ_ONLY"
    private val ROLE_CONSIGNMENT_BUYER_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_SYSTEM_ADMIN_PLASMA_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PLASMA_ORDERING__SYSTEM_ADMIN"

    private val ROLE_ASR_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__ASR"
    private val ROLE_ADMIN_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__ADMIN"
    private val ROLE_BUYER_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__BUYER"
    private val ROLE_CONSIGNMENT_BUYER_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_READONLY_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__READ_ONLY"
    private val ROLE_SYSTEM_ADMIN_ONCOL_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_ONCOL_ORDERING__SYSTEM_ADMIN"

    private val ROLE_ADMIN_INTERFACES_ADMIN_TOOL =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__INTFCWARPADMIN"
    private val ROLE_READ_ONLY_INTERFACES_ADMIN_TOOL =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__WEB_ORDERING_ADMINISTRATION__WEB_ORDERING_ADMINISTRATION__INTFCWARPREADONLY"

    private val ROLE_ADMIN_AC_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__ACUTE_CARE__ACUTE_CARE_ORDERING__ADMIN"
    private val ROLE_BUYER_AC_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__ACUTE_CARE__ACUTE_CARE_ORDERING__BUYER"
    private val ROLE_OEADMIN_VA_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__ORDER_EXPRESS-VA__VA_ORDERING__ADMIN"
    private val ROLE_OEBUYER_VA_CAPS =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__ORDER_EXPRESS-VA__VA_ORDERING__BUYER"

    private val ROLE_PREMIUM_ASR_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREMIUM__ASR"
    private val ROLE_PREMIUM_ADMIN_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREMIUM__ADMIN"
    private val ROLE_PREMIUM_BUYER_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREMIUM__BUYER"
    private val ROLE_PREMIUM_CONSIGNMENT_BUYER_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREMIUM__CONSIGNMENT_BUYER"
    private val ROLE_PREMIUM_READ_ONLY_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREMIUM__READ_ONLY"

    private val ROLE_PREMIUM_PLUS_ASR_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREPLUS__ASR"
    private val ROLE_PREMIUM_PLUS_ADMIN_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREPLUS__ADMIN"
    private val ROLE_PREMIUM_PLUS_BUYER_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREPLUS__BUYER"
    private val ROLE_PREMIUM_PLUS_CONSIGNMENT_BUYER_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREPLUS__CONSIGNMENT_BUYER"
    private val ROLE_PREMIUM_PLUS_READ_ONLY_REPORT_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_REPORTS-PREPLUS__READ_ONLY"

    private val ROLE_NEPHRO_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEPHRO_ORDERING__ASR"
    private val ROLE_NEPHRO_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEPHRO_ORDERING__ADMIN"
    private val ROLE_NEPHRO_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEPHRO_ORDERING__BUYER"
    private val ROLE_NEPHRO_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEPHRO_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_NEPHRO_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEPHRO_ORDERING__READ_ONLY"

    private val ROLE_NEURO_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEURO_ORDERING__ASR"
    private val ROLE_NEURO_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEURO_ORDERING__ADMIN"
    private val ROLE_NEURO_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEURO_ORDERING__BUYER"
    private val ROLE_NEURO_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEURO_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_NEURO_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_NEURO_ORDERING__READ_ONLY"

    private val ROLE_PRICAR_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PRICAR_ORDERING__ASR"
    private val ROLE_PRICAR_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PRICAR_ORDERING__ADMIN"
    private val ROLE_PRICAR_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PRICAR_ORDERING__BUYER"
    private val ROLE_PRICAR_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PRICAR_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_PRICAR_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_PRICAR_ORDERING__READ_ONLY"

    private val ROLE_RHEUMA_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_RHEUMA_ORDERING__ASR"
    private val ROLE_RHEUMA_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_RHEUMA_ORDERING__ADMIN"
    private val ROLE_RHEUMA_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_RHEUMA_ORDERING__BUYER"
    private val ROLE_RHEUMA_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_RHEUMA_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_RHEUMA_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_RHEUMA_ORDERING__READ_ONLY"

    private val ROLE_UROLOGY_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_UROLOGY_ORDERING__ASR"
    private val ROLE_UROLOGY_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_UROLOGY_ORDERING__ADMIN"
    private val ROLE_UROLOGY_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_UROLOGY_ORDERING__BUYER"
    private val ROLE_UROLOGY_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_UROLOGY_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_UROLOGY_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_UROLOGY_ORDERING__READ_ONLY"

    private val ROLE_GI_ORDERING_ASR_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_GI_ORDERING__ASR"
    private val ROLE_GI_ORDERING_ADMIN_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_GI_ORDERING__ADMIN"
    private val ROLE_GI_ORDERING_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_GI_ORDERING__BUYER"
    private val ROLE_GI_ORDERING_CONSIGNMENT_BUYER_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_GI_ORDERING__CONSIGNMENT_BUYER"
    private val ROLE_GI_ORDERING_READ_ONLY_SS_SPD =
        "G-EXT-GA-SPECIALTY_PHARMACEUTICAL_SERV__SPECIALTY_PHARMACEUTICAL_SERVICES__SPECIALTY_PHARMACEUTICAL_SERVICES_GI_ORDERING__READ_ONLY"

    private val ROLE_ASSIST_ADMIN =
        "G-EXT-GA-PHARMACEUTICAL_DISTRIBUTION__ACUTE_CARE__ASSIST_ADMIN__ASSIST_ADMIN"

    var retailIndUserGrpList: MutableList<String> = mutableListOf()
    var spdUserGrpList: MutableList<String> = mutableListOf()
    var ssspdUserGrpList: MutableList<String> = mutableListOf()
    var acuteCareUserGrpList: MutableList<String> = mutableListOf()
    var adminUsergrpList: MutableList<String> = mutableListOf()
    var assistAdminUserGrpList: MutableList<String> = mutableListOf()

    /**
     * Returns store front name based on mapping
     */
    fun getStoreFront(rawProgrammingCodes: String, memberGroupList: List<String>): String? {

        var storeFront: String? = EMPTY_STRING
        var ldpaGroupName: String = EMPTY_STRING
        // Construct members list group
        constructData()
        val groupNames: List<String> = memberGroupList
        groupNames.forEach { groupName ->
            val subGroupName: List<String> = groupName.split(COMMA_SEPARATOR)
            ldpaGroupName = subGroupName[ZERO].substring(THREE)
        }
        val programmingCodes: List<String> =
            rawProgrammingCodes.split(COMMA_SEPARATOR)
        for (programmingCode in programmingCodes) {
            if (programmingCode == CIM_PROGRAMMING_CODE) {
                storeFront = CIM_STORE_FRONT
                break
            } else if (programmingCode == PR_PROGRAMMING_CODE) {
                storeFront = PR_STORE_FRONT
                break
            } else if (programmingCode == ASSIST_PROGRAMMING_CODE) {
                storeFront = ASSIST_STORE_FRONT
                break
            } else if (retailIndUserGrpList.contains(ldpaGroupName)) {
                storeFront = RETAIL_INDEPENDENT_USER_GROUP
                break
            } else if (spdUserGrpList.contains(ldpaGroupName)) {
                storeFront = SPD_USER_GROUP
                break
            } else if (ssspdUserGrpList.contains(ldpaGroupName)) {
                storeFront = SS_SPD_USER_GROUP
                break
            } else if (acuteCareUserGrpList.contains(ldpaGroupName)) {
                storeFront = ACUTE_CARE_USER_GROUP
                break
            } else if (adminUsergrpList.contains(ldpaGroupName)) {
                storeFront = RETAIL_ADMIN_USER_GROUP
                break
            } else if (assistAdminUserGrpList.contains(ldpaGroupName)) {
                storeFront = ASSIST_ADMIN_USER_GROUP
                break
            }
        }
        return storeFront
    }

    /**
     * Construct member group list
     */
    private fun constructData() {
        retailIndUserGrpList.add(ROLE_ADMIN_RI_CAPS)
        retailIndUserGrpList.add(ROLE_BUYER_RI_CAPS)
        retailIndUserGrpList.add(ROLE_READONLY_RI_CAPS)
        retailIndUserGrpList.add(ROLE_ADMIN_RI_SMALL)
        retailIndUserGrpList.add(ROLE_BUYER_RI_SMALL)
        retailIndUserGrpList.add(ROLE_READONLY_RI_SMALL)
        retailIndUserGrpList.add(ROLE_BUYER_RI_NEW_CAPS)
        retailIndUserGrpList.add(ROLE_ADMIN_RI_NEW_CAPS)
        retailIndUserGrpList.add(RETAIL_INDEPENDENT_USER_GROUP)
        retailIndUserGrpList.add(ROLE_NON_ORDERING_RI_CAPS)

        adminUsergrpList.add(RETAIL_ADMIN_USER_GROUP)
        adminUsergrpList.add(ROLE_ADMINROLE_ADMIN)
        adminUsergrpList.add(ROLE_READONLY_ADMIN)
        adminUsergrpList.add(ROLE_READONLY_ADMIN_OLD)
        adminUsergrpList.add(ROLE_ADMIN_READONLY_ROLE)
        adminUsergrpList.add(ROLE_ADMIN_PO_EXPORT)
        adminUsergrpList.add(ROLE_ADMIN_INTERFACES_ADMIN_TOOL)
        adminUsergrpList.add(ROLE_READ_ONLY_INTERFACES_ADMIN_TOOL)

        adminUsergrpList.add(ROLE_ADMINROLE_OE_RUN_ADMIN)

        adminUsergrpList.add(ROLE_ADMIN_ORG_MDM_USER)

        adminUsergrpList.add(ROLE_ADMIN_ORG_TIER_REBATE_USER)

        spdUserGrpList.add(ROLE_ADMIN_SPD_CAPS)
        spdUserGrpList.add(ROLE_BUYER_SPD_CAPS)
        spdUserGrpList.add(ROLE_READONLY_SPD_CAPS)
        spdUserGrpList.add(ROLE_ASR_SPD_CAPS)
        spdUserGrpList.add(ROLE_ADMIN_SPD_SMALL)
        spdUserGrpList.add(ROLE_BUYER_SPD_SMALL)
        spdUserGrpList.add(ROLE_READONLY_SPD_SMALL)
        spdUserGrpList.add(ROLE_ASR_SPD_SMALL)
        spdUserGrpList.add(SPD_USER_GROUP)

        ssspdUserGrpList.add(ROLE_ASR_PLASMA_SS_SPD)
        ssspdUserGrpList.add(ROLE_ADMIN_PLASMA_SS_SPD)
        ssspdUserGrpList.add(ROLE_BUYER_PLASMA_SS_SPD)
        ssspdUserGrpList.add(ROLE_READONLY_PLASMA_SS_SPD)
        ssspdUserGrpList.add(ROLE_CONSIGNMENT_BUYER_PLASMA_SS_SPD)
        ssspdUserGrpList.add(ROLE_SYSTEM_ADMIN_PLASMA_SS_SPD)

        // Oncology User Group
        ssspdUserGrpList.add(ROLE_ASR_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_ADMIN_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_BUYER_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_CONSIGNMENT_BUYER_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_READONLY_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_SYSTEM_ADMIN_ONCOL_SS_SPD)
        ssspdUserGrpList.add(ROLE_SYSTEM_ADMIN_ONCOL_SS_SPD)

        // Added SPD Premium Report User Group in SS_SPD User Group - START
        ssspdUserGrpList.add(ROLE_PREMIUM_ASR_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_ADMIN_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_BUYER_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_CONSIGNMENT_BUYER_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_READ_ONLY_REPORT_SS_SPD)
        // SPD Premium Report User Group - END
        // Added SPD Premium Plus Report User Group in SS_SPD User Group - START
        ssspdUserGrpList.add(ROLE_PREMIUM_PLUS_ASR_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_PLUS_ADMIN_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_PLUS_BUYER_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_PLUS_CONSIGNMENT_BUYER_REPORT_SS_SPD)
        ssspdUserGrpList.add(ROLE_PREMIUM_PLUS_READ_ONLY_REPORT_SS_SPD)
        // SPD Premium Plus Report User Group - END

        // SPD NEPHRO User Group
        ssspdUserGrpList.add(ROLE_NEPHRO_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEPHRO_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEPHRO_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEPHRO_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEPHRO_ORDERING_READ_ONLY_SS_SPD)

        // SPD NEURO User Group
        ssspdUserGrpList.add(ROLE_NEURO_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEURO_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEURO_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEURO_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_NEURO_ORDERING_READ_ONLY_SS_SPD)

        // SPD PRICAR User Group
        ssspdUserGrpList.add(ROLE_PRICAR_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_PRICAR_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_PRICAR_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_PRICAR_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_PRICAR_ORDERING_READ_ONLY_SS_SPD)

        // SPD RHEUMA User Group
        ssspdUserGrpList.add(ROLE_RHEUMA_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_RHEUMA_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_RHEUMA_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_RHEUMA_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_RHEUMA_ORDERING_READ_ONLY_SS_SPD)

        // SPD UROLOGY User Group
        ssspdUserGrpList.add(ROLE_UROLOGY_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_UROLOGY_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_UROLOGY_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_UROLOGY_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_UROLOGY_ORDERING_READ_ONLY_SS_SPD)

        // SPD GI Ordering User Group
        ssspdUserGrpList.add(ROLE_GI_ORDERING_ASR_SS_SPD)
        ssspdUserGrpList.add(ROLE_GI_ORDERING_ADMIN_SS_SPD)
        ssspdUserGrpList.add(ROLE_GI_ORDERING_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_GI_ORDERING_CONSIGNMENT_BUYER_SS_SPD)
        ssspdUserGrpList.add(ROLE_GI_ORDERING_READ_ONLY_SS_SPD)

        ssspdUserGrpList.add(SS_SPD_USER_GROUP)
        // Acute Care Specific Portal and Store Definitions - start
        acuteCareUserGrpList.add(ROLE_ADMIN_AC_CAPS)
        acuteCareUserGrpList.add(ROLE_BUYER_AC_CAPS)
        acuteCareUserGrpList.add(ROLE_OEBUYER_VA_CAPS)
        acuteCareUserGrpList.add(ROLE_OEADMIN_VA_CAPS)
        acuteCareUserGrpList.add(ACUTE_CARE_USER_GROUP)

        assistAdminUserGrpList.add(ASSIST_ADMIN_USER_GROUP)
        assistAdminUserGrpList.add(ROLE_ASSIST_ADMIN)
    }
}